Change return type of main to use anyhow::Error for pretty printing
Before this change, when encountering an error while parsing the json,
the redmine-rs would print the following error message:
  Serde(Error("EOF while parsing a value", line: 1, column: 0))

This change allow `anyhow` to print a somewhat more useful message:
  Error: failed to deserialize an instance from a string of JSON text: EOF while parsing a value at line 1 column 0

  Caused by:
      EOF while parsing a value at line 1 column 0

Signed-off-by: Francis Deslauriers <fdeslaur@gmail.com>